GrandReal/Controllers/DocsController.cs
using GrandReal.DBconnection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GrandReal.Controllers
{
    public class DocsController : Controller
    {
        GrandrealContext context;
        int idUser;
        public DocsController()
        {
            context = new GrandrealContext();
        }
        // GET: DocsController
        public ActionResult Index()
        {
            //var docs = context.Contracts.Where(a=> a.id)
            return View();
        }
        public int? checkAuth()
        {
            //Не получится засунуть в конструктор, так как там контекст запроса не инициализирован

            if (HttpContext.Request.Cookies["idUser"] != null)
                if (Int32.TryParse(HttpContext.Request.Cookies["idUser"], out int id))
                {
                    idUser = id;
                    return id;
                }

            return null;
        }
    }
}

GrandReal/Controllers/ObjectsController.cs
using GrandReal.DBconnection;
using GrandReal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using Microsoft.Extensions.Hosting.Internal;
using System.Linq;

namespace GrandReal.Controllers
{
    public class ObjectsController : Controller
    {
        GrandrealContext context;
        int idUser;
        
        public ObjectsController()
        {
            context = new GrandrealContext();
        }
        public ActionResult Index() 
        {
            #region проверка на авторизацию
            if (checkAuth() == null)
                return View("../Auth/Auth");
            #endregion
            //Заголовок в шапке страницы
            ViewData["Title"] = "Объекты недвижимости";

            //Сбор данных
            var objects = context.ObjectViews.Where(a=>a.IsActive == 1).ToList();
            var imagesObjects = context.ImagesObjects.ToList();
            var FavoriteClientObjects = context.FavoriteClientObjects.Where(a=>a.Client == idUser).Select(a=>a.Object).ToList();
            var AplicationsClient = context.Applications.Where(a=>a.IdClient == idUser).Select(a=>a.IdObject).ToList();
            
            //Укомлектовка в модельку
            var model = new ObjectsModel()
            {
                Objects = objects,
                ImagesObjects = imagesObjects,
                FavoriteClientObjects = FavoriteClientObjects,
                AplicationsClient = AplicationsClient
            };
            return View(model);
        }
        /// <summary>
        /// Лайк объекта
        /// </summary>
        /// <param name="idObject">ИД объекта всё просто</param>
        /// <returns>объект с текстом о результате</returns>
        public object LikeObject(int idObject) {
            try
            {
                #region проверка на авторизацию
                if (checkAuth() == null)
                    return View("../Auth/Auth");
                #endregion

                #region проверка, не поставлен ли лайк уже

                var checkLike = context.FavoriteClientObjects.Any(a=>a.Client == idUser && a.Object == idObject);
                if (checkLike) return new { error = "Лайк уже стоит, обратитесь к раззарботчику" };

                #endregion

                int lastId = context.FavoriteClientObjects.Max(x => x.Id);
                var likeRecord = new FavoriteClientObject() { 
                    Id = lastId+1,
                    Client = idUser,
                    Object = idObject,
                };
                context.FavoriteClientObjects.Add(likeRecord);
                context.SaveChanges();
                return new { message = "Успешно" };
            }
            catch (Exception ex)
            {
                return new { error = ex.Message };
            }
        }
        /// <summary>
        /// Аналогично лайку
        /// </summary>
        /// <param name="idObject"></param>
        /// <returns></returns>
        public object RemoveLikeObject(int idObject) {
            try
            {
                #region проверка на авторизацию
                if (checkAuth() == null)
                    return View("../Auth/Auth");
                #endregion

                var likeRecord = context.FavoriteClientObjects.FirstOrDefault(a=>a.Client == idUser && a.Object == idObject);

                #region проверка, есть ли лайк в базе

                if (likeRecord == null) return new { error = "Лайк не найден, обратитесь к раззарботчику" };

                #endregion

                context.FavoriteClientObjects.Remove(likeRecord);
                context.SaveChanges();
                return new { message = "Успешно" };
            }
            catch (Exception ex)
            {
                return new { error = ex.Message };
            }
        }
        /// <summary>
        /// Проверка на авторизацию, обязательна, если используется idUser переменная
        /// </summary>
        /// <returns>int id user если пришло в куки и null если не пришло</returns>
        public int? checkAuth() {
            //Не получится засунуть в конструктор, так как там контекст запроса не инициализирован

            if (HttpContext.Request.Cookies["idUser"] != null)
                if (Int32.TryParse(HttpContext.Request.Cookies["idUser"], out int id))
                {
                    idUser = id;
                    return id;
                }

            return null;
        }
        /// <summary>
        /// Страница избранных объектов
        /// </summary>
        /// <returns></returns>
        public ActionResult FavoriteObjects()
        {
            #region проверка на авторизацию
            if (checkAuth() == null)
                return View("../Auth/Auth");
            #endregion

            ViewData["Title"] = "Избранные объекты";

            //Сбор данных
            var FavoriteClientObjects = context.FavoriteClientObjects.Where(a => a.Client == idUser).Select(a => a.Object).ToList();
            var objects = context.ObjectViews.Where(a => FavoriteClientObjects.Contains(a.IdObject) && a.IsActive == 1).ToList();
            var imagesObjects = context.ImagesObjects.Where(a=> FavoriteClientObjects.Contains(a.Object)).ToList();
            var AplicationsClient = context.Applications.Where(a => a.IdClient == idUser).Select(a => a.IdObject).ToList();

            //Укомлектовка в модельку
            var model = new ObjectsModel()
            {
                Objects = objects,
                ImagesObjects = imagesObjects,
                FavoriteClientObjects = FavoriteClientObjects,
                AplicationsClient = AplicationsClient
            };
            return View("Index", model);
        }
        /// <summary>
        /// Создание заявки на покупку объекта
        /// </summary>
        /// <param name="idObject"></param>
        /// <returns></returns>
        /// TODO: не хватает ИД содрудника, так и не понял как его достать
        public object SubmitApplication(int idObject)
        {
            try
            {
                #region проверка на авторизацию
                if (checkAuth() == null)
                    return View("../Auth/Auth");
                #endregion

                var application = new Application()
                {
                    IdClient = idUser,
                    IdObject = idObject
                };
                context.Applications.Add(application);
                context.SaveChanges();

                return new { message = "Заявка успешно создана" };
            }
            catch (Exception ex)
            {
                return new { error = ex.Message };
            }

            
        }
        /// <summary>
        /// Страница Заявок
        /// </summary>
        /// <returns></returns>
        public ActionResult ApplicationsObjects()
        {
            #region проверка на авторизацию
            if (checkAuth() == null)
                return View("../Auth/Auth");
            #endregion
            ViewData["Title"] = "Заявки";

            var FavoriteClientObjects = context.FavoriteClientObjects.Where(a => a.Client == idUser).Select(a => a.Object).ToList();               
            var AplicationsClient = context.Applications.Where(a => a.IdClient == idUser).Select(a => a.IdObject).ToList();
            var objects = context.ObjectViews.Where(a => AplicationsClient.Contains(a.IdObject) && a.IsActive == 1).ToList();
            var imagesObjects = context.ImagesObjects.Where(a => AplicationsClient.Contains(a.Object ?? 0)).ToList();

            var model = new ObjectsModel()
            {
                Objects = objects,
                ImagesObjects = imagesObjects,
                FavoriteClientObjects = FavoriteClientObjects,
                AplicationsClient = AplicationsClient
            };
            return View("Index", model);
        }
        /// <summary>
        /// Страница для заявки на продажу объекта
        /// </summary>
        /// <returns></returns>
        public ActionResult SellObject()
        {
            #region проверка на авторизацию
            if (checkAuth() == null)
                return View("../Auth/Auth");
            #endregion
            ViewData["Title"] = "Продать объект";


            return View("SellObject");
        }
        /// <summary>
        /// Страница для заявки на личную заявку подбора объекта
        /// </summary>
        /// <returns></returns>
        public ActionResult PersonalRequestSearchObject()
        {
            #region проверка на авторизацию
            if (checkAuth() == null)
                return View("../Auth/Auth");
            #endregion
            ViewData["Title"] = "Создать личную заявку";


            return View("PersonalRequestSearchObject");
        }
    }
}

GrandReal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@(ViewData["Title"])</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GrandReal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
    @* Тоже костыль для скрытия шапки при авторизации *@
    @if (ViewData["Title"].ToString() != "Авторизация")
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GrandRealt</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="Index">Объекты недвижимости</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="FavoriteObjects">Избранные объекты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="ApplicationsObjects">Заявки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Docs" asp-action="Index">Документы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="SellObject">Продать</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="PersonalRequestSearchObject">Оставить личную заявку</a>
                            </li>
                        </ul>
                    </div>
                    <div id="userAuth" class="d-flex">
                        <p id="userName" class="mb-0 mt-2 me-4"></p>
                        <button id="toLogin" class="btn btn-outline-primary ps-3 pe-3">Выход</button>
                    </div>
                </div>
            </nav>
        </header>
    }
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @* Моё модальное окно думаю разберёшься, написано не сложно по сравнению с решениями из инета*@
    <div class="myModalBackground myModalHide">
        <div class="myModal">
            <div class="titleModal">
                <h4 class="m-0 p-0">Внимание</h4>
                <div class="cross" onclick="closeMyAlert()"></div>
            </div>
            <div class="bodyModal d-flex">
                @* <img id="loadGif" src="~/img/load.gif" />  *@
                <div class="fs-5">Произошёл сбой</div>
                <p class="fs-5"></p>
            </div>
            <div class="footerModal">
                <button class="btn btn-outline-primary px-3 py-1 mx-3" onclick="closeMyAlert()">Отмена</button>
                <button class="btn btn-primary px-3 py-1">Продолжить</button>
            </div>
        </div>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GrandReal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/helper.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>